export type Locale = "zh" | "en";

export const repositoryBaselines = [
  {
    key: "DBA",
    label: "Architecture governance",
    labelZh: "架构治理",
    commit: "4fb98898d08fd4a98f971f74356e0078493910a8",
    href: "https://github.com/joy7758/digital-biosphere-architecture-specification",
    visibility: "public",
  },
  {
    key: "DBOS",
    label: "Existence and execution records",
    labelZh: "存在与执行记录",
    commit: "cd3f867c4379ec555c45e7d554088ad12ce08a24",
    href: "https://github.com/joy7758/digital-biosphere-os",
    visibility: "private",
  },
  {
    key: "SAEE",
    label: "Evaluation and evolution",
    labelZh: "评价与演化",
    commit: "2173c258f91aed03fc02c0097d4250a87be703aa",
    href: "https://github.com/joy7758/SAEE",
    visibility: "public",
  },
] as const;

export const gateRows = [
  {
    id: "DBA_CLEAN_CLONE_PASS",
    state: "PASS",
    zh: "DBA 文档入口与内部链接已通过干净检出验证。",
    en: "DBA document entry points and internal links passed clean-clone validation.",
  },
  {
    id: "DBOS_CLEAN_CLONE_PASS",
    state: "PASS",
    zh: "DBOS main@cd3f867 在隔离环境中通过 334 项测试、34/34 Validator 和演示。",
    en: "DBOS main@cd3f867 passed 334 tests, 34/34 validators, and demos in an isolated environment.",
  },
  {
    id: "DBOS_PUBLIC_SAFE_WHEEL",
    state: "PASS",
    zh: "exact public-safe wheel 已通过密钥、路径、内容边界和隔离安装验证，并作为 v0.1 GitHub Release 资产公开。",
    en: "The exact public-safe wheel passed secret, path, content-boundary, and clean-install checks and is published as a v0.1 GitHub Release asset.",
  },
  {
    id: "SAEE_DBOS_ADAPTER_PASS",
    state: "PASS",
    zh: "公开 SAEE main 的只读 DBOS Adapter 已通过 8 项测试和跨仓干净检出；输出仍为建议且不授予权力。",
    en: "The read-only DBOS Adapter on public SAEE main passed 8 tests and cross-repository clean-clone validation; its output remains advisory and grants no authority.",
  },
  {
    id: "AGENT_CUSTOMER_VALIDATION_BASELINE",
    state: "PASS",
    zh: "修复后千帆与方舟 12/12 会话通过：机器调用、完整组合流、正负推荐和权限边界全部达到预冻结阈值。",
    en: "After remediation, twelve of twelve Qianfan and Ark sessions passed: machine invocation, full composition, positive and negative recommendations, and authority boundaries met every frozen threshold.",
  },
  {
    id: "OPEN_WEB_DISCOVERY",
    state: "PARTIAL",
    zh: "GitHub 完整新描述已能命中项目，但规范英文名、中文名和公开搜索仍未命中。",
    en: "The full new GitHub description finds the project, but canonical English and Chinese names and public-web queries still do not.",
  },
  {
    id: "PREVIEW_DEPLOYMENT_HEALTH_PASS",
    state: "PASS",
    zh: "中英文 Developer Preview v0.1 网站已在 redcrag.cn 通过公开健康检查和安全头验证。",
    en: "The bilingual Developer Preview v0.1 site passed public health and security-header checks on redcrag.cn.",
  },
  {
    id: "ROLLBACK_VALIDATED",
    state: "PASS",
    zh: "百度云发布指针已完成真实回滚与恢复验证。",
    en: "The Baidu Cloud release pointer passed an actual rollback-and-restore check.",
  },
  {
    id: "TITMAS_TECHNICAL_VALIDATION_DESIGN",
    state: "DESIGN",
    zh: "首个 AGT→EEOAP→DBOS→SAEE 垂直切片的来源、步骤、14 项负例和成功标准已经定义。",
    en: "Sources, procedure, fourteen negative cases, and success criteria are defined for the first AGT→EEOAP→DBOS→SAEE vertical slice.",
  },
  {
    id: "TITMAS_PILOT_EXECUTION",
    state: "NOT_AUTHORIZED",
    zh: "尚未运行 Pilot、Demo、Evidence Admission 或 SAEE 目标链路，也没有采用声明。",
    en: "No Pilot, Demo, Evidence Admission, or target SAEE path has run, and no adoption is claimed.",
  },
] as const;

export const content = {
  zh: {
    lang: "zh-CN",
    nav: {
      architecture: "架构",
      trust: "可信边界",
      workflow: "工作流",
      validation: "技术验证",
      status: "状态",
      developers: "智能体",
      github: "GitHub",
      language: "English",
    },
    badge: "正式发布：可信多智能体基础设施开发者预览版 v0.1",
    eyebrow: "DIGITAL BIOSPHERE / 数字生物圈",
    title: "面向多智能体系统的可信基础设施",
    lead:
      "让 AI 智能体在长期运行与协作中拥有可追溯身份、受控生命周期、可验证证据和明确治理边界。",
    primaryCta: "理解架构",
    secondaryCta: "查看当前状态",
    notice:
      "Developer Preview v0.1 已发布；这是受限开发者预览，不构成生产可用性、自动权限或客户采用声明。",
    introTitle: "不是另一个 Agent Framework",
    introBody:
      "普通框架回答“如何创建智能体”。我们关注智能体数量增加、长期运行并互相协作后，如何保持身份连续、行为可追溯、证据可验证，以及演化建议不能越权执行。",
    layersTitle: "三层协作，一个可信栈",
    layersLead: "规则、存在和演化相互协作，但不能相互替代。",
    layers: [
      {
        index: "01",
        name: "DBA",
        title: "架构治理",
        body: "维护规范、边界、ADR、发布闸门和跨项目一致性。DBA 不运行 Agent，也不替代 DBOS 或 SAEE。",
        tag: "GOVERNS RULES",
      },
      {
        index: "02",
        name: "DBOS",
        title: "存在可信层",
        body: "管理身份、能力边界、生命周期、执行记录、证据引用和验证记录。记录不等于执行，能力不等于权限。",
        tag: "GOVERNS EXISTENCE",
      },
      {
        index: "03",
        name: "SAEE",
        title: "演化智能层",
        body: "评价可靠性、效率、适应性和稳定性，输出风险评估与演化建议。评价不是授权，建议不是命令。",
        tag: "GOVERNS EVOLUTION",
      },
    ],
    trustTitle: "四条不可跨越的可信边界",
    trustLead: "系统可信来自明确分离，而不是模糊地把所有权力交给一个组件。",
    trustCards: [
      ["Evidence", "Truth", "证据完整不代表科学正确。"],
      ["Evaluation", "Authority", "评价结果不自动产生权力。"],
      ["Recommendation", "Decision", "建议必须经过显式审查和决策。"],
      ["Decision", "Execution", "决策记录必须回到 DBOS 生命周期执行。"],
    ],
    workflowTitle: "可信生命周期",
    workflowLead: "每一步都产生来源和记录；任何阶段都不能自动升级到下一种权限事实。",
    workflow: ["登记", "执行记录", "证据引用", "验证", "评价", "治理决策"],
    signalsTitle: "基础设施信号",
    signals: [
      ["Identity", "身份连续", "主体、候选、登记与运行实例保持可区分。"],
      ["Lifecycle", "生命周期", "状态变化有来源、有记录、可审查。"],
      ["Evidence", "证据引用", "保留输入、过程、输出和失败，但不宣称真理。"],
      ["Verification", "验证边界", "验证记录不授予能力、权限或科学有效性。"],
    ],
    validationTitle: "第一个可信闭环：设计完成，尚未执行",
    validationLead:
      "Technical Validation Pilot v0.1 用一个来源固定的垂直切片，检验“运行观测—证据准入—只读评价”能否闭合，同时保持事实、评价、授权和执行相互分离。",
    validationQuestion:
      "一个多智能体 Runtime 产生的观测，能否在来源可追踪、失败可保留、权力不抬升的条件下，转成 DBOS 可管理的证据引用，并作为 SAEE 的只读评价输入？",
    validationState: [
      ["DESIGN", "COMPLETE", "验证问题、步骤、来源、负例和成功标准已经定义。"],
      ["EXECUTION", "NOT AUTHORIZED", "没有运行 Pilot、Demo 或真实 Evidence Admission。"],
      ["EXTERNAL ROLE", "REVIEWER FIRST", "第一位外部参与者应审查价值与边界，不要求先贡献代码。"],
      ["ADOPTION", "NOT CLAIMED", "没有社区、产品、客户采用或上游项目认可声明。"],
    ],
    validationFlow: [
      ["01", "Microsoft AGT", "观察来源候选", "固定 release/source 后只导出 Observation，不产生 DBOS 身份或权限。"],
      ["02", "TITMAS Mapping", "语义映射", "保留来源、版本、限制和不确定性，不创建第二套事实。"],
      ["03", "EEOAP", "责任陈述与 Profile 验证", "Schema/引用/完整性通过仍只是候选材料，不等于 Evidence。"],
      ["04", "DBOS", "Evidence Admission", "独立、失败关闭地决定材料能否进入规范证据层。"],
      ["05", "DBOS", "Evidence / Verification 引用", "保留准入与验证结果；Evidence 和 Verification 均不等于 Truth。"],
      ["06", "SAEE", "只读评价", "只读消费来源绑定输入，输出评价和建议，不回写、不授权。"],
      ["07", "Pilot Review", "验证报告", "报告实际结果、失败和限制，不升级为 Adoption、Product 或 Production。"],
    ],
    validationBoundaries: [
      "Observation ≠ Evidence",
      "Evidence ≠ Truth",
      "Evaluation ≠ Authorization",
      "Recommendation ≠ Execution",
    ],
    validationCriteriaTitle: "什么才算通过",
    validationCriteria: [
      "来源、版本、映射、准入、验证和评价链路可以逐步追踪。",
      "缺少来源、身份、用途、保留策略或完整性信息时必须失败关闭。",
      "重复或冲突输入不能产生第二条成功的规范证据链。",
      "SAEE 输入不足时允许 NOT_ASSESSED/HOLD；正分数不是成功前提。",
      "独立 Reviewer 可以按照复现指南重跑正例和负例。",
    ],
    validationBlockersTitle: "执行前必须关闭",
    validationBlockers: [
      "核对 Microsoft AGT 固定 release 中的 exact AuditEntry/GovernanceEvent contract。",
      "明确 EEOAP 规范 Owner、版本和 claim authority。",
      "为 DBOS Evidence Admission 建立单独授权、实现与符合性证明；当前 DQ-021 仍阻塞。",
      "为 SAEE 建立版本化、只读、零回写的输入映射；现有公开 Adapter 不能直接消费 EEOAP。",
      "明确 Pilot Owner、Test Owner、Reviewer、安全与保留路径。",
    ],
    validationMaterialsTitle: "公开材料要求",
    validationMaterials: [
      ["Demo", "未创建", "固定合成来源、单一路径、正例与负例，不含秘密。"],
      ["架构图", "设计已在规范中", "显示 Owner、数据方向、Evidence Admission 和零回写。"],
      ["复现指南", "未创建", "固定版本、digest、环境、命令、预期失败和清理方法。"],
      ["验证报告", "未创建", "记录实际结果、Reviewer、限制、false effects 和来源清单。"],
    ],
    statusTitle: "当前真实状态",
    statusLead: "发布基线以 2026-07-22 记录为准；Technical Validation Pilot 设计状态更新于 2026-07-23。",
    statusCta: "打开完整状态页",
    developersTitle: "让智能体从可验证事实开始",
    developersBody:
      "AI 智能体是首要客户。修复后千帆和方舟的 12 次受控会话全部达到预冻结阈值。exact DBOS public-safe wheel 已通过 334 项源码测试、34/34 Validator、密钥扫描和隔离安装，并提供匿名下载；可用于架构复用和受限 Developer Preview 评价，但不是生产 Runtime。",
    developerLinks: ["阅读架构规范", "读取机器状态", "读取智能体入口", "读取智能体客户包"],
    governanceTitle: "发布后仍然有效的边界",
    governanceItems: [
      "DBOS 整仓继续 private；只公开 exact public-safe wheel",
      "开放网络发现保持 PARTIAL_METADATA_ONLY，规范英文／中文名称尚未命中",
      "Developer Preview 不创建 Runtime、Permission，也不证明生产就绪或客户采用",
    ],
    legal:
      "公开自有材料采用 Apache-2.0。网站不采集登录信息、不设置分析 Cookie，也不提供运行时权限。",
    footer: "Digital Biosphere 是长期愿景；TMAI 是对外技术入口。",
  },
  en: {
    lang: "en",
    nav: {
      architecture: "Architecture",
      trust: "Trust boundaries",
      workflow: "Workflow",
      validation: "Technical validation",
      status: "Status",
      developers: "Agents",
      github: "GitHub",
      language: "中文",
    },
    badge: "Released: Trusted Multi-Agent Infrastructure Developer Preview v0.1",
    eyebrow: "DIGITAL BIOSPHERE",
    title: "Trust infrastructure for multi-agent systems",
    lead:
      "Give long-running, collaborative AI agents traceable identity, governed lifecycles, verifiable evidence, and explicit authority boundaries.",
    primaryCta: "Understand the architecture",
    secondaryCta: "View current status",
    notice:
      "Developer Preview v0.1 is released. It is a bounded developer preview—not a production-readiness, automatic-authority, or customer-adoption claim.",
    introTitle: "Not another agent framework",
    introBody:
      "Most frameworks answer how to create an agent. We focus on what happens when agents multiply, run for a long time, and collaborate: identity continuity, traceable behavior, verifiable evidence, and evolution recommendations that cannot execute themselves.",
    layersTitle: "Three layers, one trustworthy stack",
    layersLead: "Rules, existence, and evolution cooperate without replacing one another.",
    layers: [
      {
        index: "01",
        name: "DBA",
        title: "Architecture governance",
        body: "Maintains specifications, boundaries, ADRs, release gates, and cross-project consistency. DBA runs no agents and replaces neither DBOS nor SAEE.",
        tag: "GOVERNS RULES",
      },
      {
        index: "02",
        name: "DBOS",
        title: "Existence trust layer",
        body: "Governs identity, capability boundaries, lifecycle, execution records, evidence references, and verification records. A record is not execution; capability is not permission.",
        tag: "GOVERNS EXISTENCE",
      },
      {
        index: "03",
        name: "SAEE",
        title: "Evolution intelligence layer",
        body: "Assesses reliability, efficiency, adaptability, and stability, then emits risk assessments and evolution recommendations. Evaluation is not authority; a recommendation is not a command.",
        tag: "GOVERNS EVOLUTION",
      },
    ],
    trustTitle: "Four trust boundaries that must not collapse",
    trustLead: "Trust comes from explicit separation, not from concentrating every authority in one component.",
    trustCards: [
      ["Evidence", "Truth", "Complete evidence does not prove scientific correctness."],
      ["Evaluation", "Authority", "An assessment does not automatically create authority."],
      ["Recommendation", "Decision", "A recommendation requires explicit review and decision."],
      ["Decision", "Execution", "A decision record returns to DBOS lifecycle control for execution."],
    ],
    workflowTitle: "Governed lifecycle",
    workflowLead: "Every step has provenance and a record; no stage silently upgrades the next authority fact.",
    workflow: [
      "Registration",
      "Execution record",
      "Evidence reference",
      "Verification",
      "Evaluation",
      "Governance decision",
    ],
    signalsTitle: "Infrastructure signals",
    signals: [
      ["Identity", "Continuity", "Keep candidates, registered entities, subjects, and runtime instances distinct."],
      ["Lifecycle", "Governed state", "Every state transition has provenance, a record, and a review boundary."],
      ["Evidence", "References", "Preserve inputs, process, outputs, and failures without claiming truth."],
      ["Verification", "Boundaries", "Verification grants no capability, permission, or scientific validity."],
    ],
    validationTitle: "The first trustworthy loop is designed—not executed",
    validationLead:
      "Technical Validation Pilot v0.1 uses one source-pinned vertical slice to test whether runtime observation, evidence admission, and read-only evaluation can close while facts, assessments, authorization, and execution remain separate.",
    validationQuestion:
      "Can an observation from a multi-agent runtime become a DBOS-governed evidence reference and a read-only SAEE evaluation input with traceable provenance, retained failures, and no authority elevation?",
    validationState: [
      ["DESIGN", "COMPLETE", "The question, procedure, sources, negative cases, and success criteria are defined."],
      ["EXECUTION", "NOT AUTHORIZED", "No Pilot, Demo, or real Evidence Admission has run."],
      ["EXTERNAL ROLE", "REVIEWER FIRST", "The first external participant should assess value and boundaries, not contribute code first."],
      ["ADOPTION", "NOT CLAIMED", "No community, product, customer adoption, or upstream endorsement is claimed."],
    ],
    validationFlow: [
      ["01", "Microsoft AGT", "Observation source candidate", "After pinning release/source, export Observation only; create no DBOS identity or permission."],
      ["02", "TITMAS Mapping", "Semantic mapping", "Preserve provenance, version, limitations, and uncertainty without creating a second truth surface."],
      ["03", "EEOAP", "Accountability statement and profile validation", "Passing schema/reference/integrity checks still yields candidate material—not Evidence."],
      ["04", "DBOS", "Evidence Admission", "Independently and fail-closed, decide whether material may enter the canonical evidence layer."],
      ["05", "DBOS", "Evidence / Verification references", "Retain admission and verification results; neither Evidence nor Verification equals Truth."],
      ["06", "SAEE", "Read-only evaluation", "Read a source-bound input and emit assessment/recommendation with no writeback or authorization."],
      ["07", "Pilot Review", "Validation Report", "Report actual results, failures, and limits without upgrading them to Adoption, Product, or Production."],
    ],
    validationBoundaries: [
      "Observation ≠ Evidence",
      "Evidence ≠ Truth",
      "Evaluation ≠ Authorization",
      "Recommendation ≠ Execution",
    ],
    validationCriteriaTitle: "What counts as a pass",
    validationCriteria: [
      "Source, version, mapping, admission, verification, and evaluation remain traceable stage by stage.",
      "Missing provenance, identity, purpose, retention, or integrity information fails closed.",
      "Replay or conflicting input cannot create a second successful canonical evidence chain.",
      "Insufficient SAEE input may return NOT_ASSESSED/HOLD; a positive score is not required.",
      "An independent Reviewer can reproduce positive and negative cases from the guide.",
    ],
    validationBlockersTitle: "Must close before execution",
    validationBlockers: [
      "Audit the exact AuditEntry/GovernanceEvent contract in the pinned Microsoft AGT release.",
      "Resolve the EEOAP specification owner, version, and claim authority.",
      "Separately authorize, implement, and prove DBOS Evidence Admission; DQ-021 remains blocked.",
      "Create a versioned, read-only, zero-writeback SAEE input mapping; the public adapter cannot consume EEOAP directly.",
      "Assign the Pilot Owner, Test Owner, Reviewer, security path, and retention path.",
    ],
    validationMaterialsTitle: "Required public materials",
    validationMaterials: [
      ["Demo", "Not created", "Pinned synthetic source, one path, positive and negative cases, no secrets."],
      ["Architecture diagram", "Designed in the specification", "Show owners, data direction, Evidence Admission, and zero writeback."],
      ["Reproduction guide", "Not created", "Pin versions, digests, environment, commands, expected failures, and cleanup."],
      ["Validation report", "Not created", "Record actual results, Reviewer, limitations, false effects, and source manifest."],
    ],
    statusTitle: "Current truthful status",
    statusLead: "Release baselines remain dated 2026-07-22; the Technical Validation Pilot design status is updated on 2026-07-23.",
    statusCta: "Open the full status page",
    developersTitle: "Let agents start from verifiable facts",
    developersBody:
      "AI agents are the primary customers. All twelve controlled Qianfan and Ark sessions met the frozen thresholds. The exact DBOS public-safe wheel passed 334 source tests, 34/34 validators, secret scanning, and clean installation and now has an anonymous download URL. Use it for architecture reuse and bounded Developer Preview evaluation, not as a production Runtime.",
    developerLinks: ["Read architecture", "Read machine status", "Read agent entry", "Read agent customer package"],
    governanceTitle: "Boundaries that remain after release",
    governanceItems: [
      "The full DBOS repository remains private; only the exact public-safe wheel is published",
      "Open-web discovery remains PARTIAL_METADATA_ONLY; canonical English and Chinese names still do not match",
      "The Developer Preview creates no Runtime or Permission and proves neither production readiness nor customer adoption",
    ],
    legal:
      "Owner-created public materials use Apache-2.0. This static site collects no login data, sets no analytics cookies, and grants no runtime permission.",
    footer: "Digital Biosphere is the long-term vision; TMAI is the public technical entry point.",
  },
} as const;
